parameters:
#    cms_boutique.example.class: CMS\BoutiqueBundle\Example

services:
#    cms_boutique.example:
#        class: %cms_boutique.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
